### ISSUE TITLE
How to use both RTM and full api at the same time?

### ISSUE THREAD

**Issue by zifeo** [gilbertw1/slack-scala-client#40]
https://github.com/gilbertw1/slack-scala-client/commit/cc4aa2954d7cafeae347e985890b295369f02ab1#diff-2e07d918d248fe7047922c7ba132eb5eR30 blocked the usage of the `BlockingSlackClient` directly. What should we use instead? Some methods such as `openIm()` are not accessible through RTM yet, right?

**Comment by gilbertw1** [comment]
Hi, the fact that the ```SlackRtmClient``` uses a ```BlockingSlackApiClient``` internally to retrieve the RTM url for a new rtm session is more of an implementation detail than anything else, and wasn't intended to be part of it's public interface.

The ```BlockingSlackApiClient``` is a public part of the api for this library and requires no additional overhead to creating multiple instances. You could easily create a new one:

    import slack.api.BlockingSlackApiClient
    val apiClient = BlockingSlackApiClient(token)

Additionally, there's a more concurrent friendly version you can use that works with futures instead of blocking: ```SlackApiClient```. Sorry for the confusion, my intention was to clean up the public interface to some of these classes and hide some of these outstanding implementation detail.

Let me know if that solves your problem!

**Comment by zifeo** [comment]
Thanks for the answer. I feel it would be cleaner to have an official way of reaching other methods through the RTM. Blocking inside an actor is not the best solution indeed, but using `Future`-based api without proper execution context is not satisfying either. Do you plan to add all methods for the RTM version?

**Comment by gilbertw1** [comment]
Unfortunately, the RTM api is very limited and only allows for a few actions to be performed using the websocket connection, primarily just sending messages and indicating typing. All other actions, need to be performed using the REST api.

I'm not entirely convinced that coupling the REST api client to the RTM client would be cleaner than allowing the user to use these tools individually (or together) as the user sees fit. The RTM api and the REST api are both very different things and each client is scoped specifically to the api they are attempting to model.

Additionally, after migrating from dispatch to akka-http as the http client, the async version of the api requires an implicit ActorSystem in scope instead of an ExecutionContext.

Perhaps an 'all inclusive' client could be added that allows you to use the RTM api and has all REST api method baked in, but in that case it'd really only be wrapping the other two clients. Additionally, you'll run into weird cases, like having two different ```sendMessage``` functions (one that uses the REST api, and one that will send via the RTM websocket).

**Comment by zifeo** [comment]
In this case, it sounds reasonable to keep them separate, thanks for the insight 👍
